import os
import django

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'webapps.settings')
django.setup()

from idiomapp.models import Idiom  # Replace 'your_app_name' with the name of your app

idioms_data = [
    {"idiom": "卧薪尝胆", "pronunciation": "wò xīn cháng dǎn", "translation": "Sleeping on firewood and tasting gall",
     "explanation": "Enduring hardship to prepare for revenge or future success."},
    {"idiom": "唾手可得", "pronunciation": "tuò shǒu kě dé", "translation": "Obtainable by spitting on your hands",
     "explanation": "Something that is very easy to get."},
    {"idiom": "朝三暮四", "pronunciation": "zhāo sān mù sì", "translation": "Three in the morning, four in the evening",
     "explanation": "Frequently changing one's mind; inconsistent behavior."},
    {"idiom": "一鼓作气", "pronunciation": "yī gǔ zuò qì", "translation": "Raising the spirit in one go",
     "explanation": "Completing something in one go without losing momentum."},
    {"idiom": "指手画脚", "pronunciation": "zhǐ shǒu huà jiǎo", "translation": "Pointing hands and drawing feet",
     "explanation": "Bossing people around or making excessive comments."},
    {"idiom": "水落石出", "pronunciation": "shuǐ luò shí chū",
     "translation": "When the water recedes, the rocks appear",
     "explanation": "The truth will eventually be revealed."},
    {"idiom": "得意忘形", "pronunciation": "dé yì wàng xíng", "translation": "Forgetting oneself in success",
     "explanation": "Becoming overconfident and careless after success."},
    {"idiom": "亡命之徒", "pronunciation": "wáng mìng zhī tú", "translation": "A fugitive from death",
     "explanation": "A desperate person who risks everything."},
    {"idiom": "一帆风顺", "pronunciation": "yī fān fēng shùn", "translation": "A smooth sail",
     "explanation": "Having a smooth and successful journey or process."},
    {"idiom": "心猿意马", "pronunciation": "xīn yuán yì mǎ", "translation": "Heart like a monkey, mind like a horse",
     "explanation": "A restless heart and an unsettled mind."},
    {"idiom": "画蛇添足", "pronunciation": "huà shé tiān zú", "translation": "Drawing a snake and adding feet",
     "explanation": "Ruining something by unnecessary additions; gilding the lily."},
    {"idiom": "守株待兔", "pronunciation": "shǒu zhū dài tù", "translation": "Watching a tree stump waiting for rabbits",
     "explanation": "Waiting passively for opportunities instead of actively seeking them."},
    {"idiom": "塞翁失马", "pronunciation": "sài wēng shī mǎ", "translation": "The old man at the frontier lost his horse",
     "explanation": "A blessing in disguise; misfortune may be an actual blessing."},
    {"idiom": "掩耳盗铃", "pronunciation": "yǎn ěr dào líng", "translation": "Covering ears while stealing a bell",
     "explanation": "Self-deception; refusing to face reality."},
    {"idiom": "四面楚歌", "pronunciation": "sì miàn chǔ gē", "translation": "Chu songs on all sides",
     "explanation": "Being surrounded by enemies; in a desperate situation."},
    {"idiom": "纸上谈兵", "pronunciation": "zhǐ shàng tán bīng", "translation": "Discussing warfare on paper",
     "explanation": "Armchair strategizing; impractical theorizing."},
    {"idiom": "井底之蛙", "pronunciation": "jǐng dǐ zhī wā", "translation": "Frog at the bottom of a well",
     "explanation": "Having a narrow view of the world; provincialism."},
    {"idiom": "杯弓蛇影", "pronunciation": "bēi gōng shé yǐng", "translation": "Mistaking the reflection of a bow in a cup for a snake",
     "explanation": "Being overly suspicious; seeing dangers where none exist."},
    {"idiom": "如鱼得水", "pronunciation": "rú yú dé shuǐ", "translation": "Like a fish in water",
     "explanation": "Being in one's element; in an ideal environment."},
    {"idiom": "胸有成竹", "pronunciation": "xiōng yǒu chéng zhú", "translation": "Having a bamboo in mind",
     "explanation": "Having a well-thought-out plan; being fully prepared."},
    {"idiom": "风马牛不相及", "pronunciation": "fēng mǎ niú bù xiāng jí", "translation": "The horse in the wind has nothing to do with the ox",
     "explanation": "Completely unrelated; irrelevant to each other."},
    {"idiom": "对牛弹琴", "pronunciation": "duì niú tán qín", "translation": "Playing the lute to a cow",
     "explanation": "Addressing the wrong audience; wasting effort."},
    {"idiom": "狐假虎威", "pronunciation": "hú jiǎ hǔ wēi", "translation": "The fox borrows the tiger's power",
     "explanation": "Using someone else's authority to intimidate others."},
    {"idiom": "画龙点睛", "pronunciation": "huà lóng diǎn jīng", "translation": "Drawing a dragon and dotting its eyes",
     "explanation": "Adding the finishing touch that brings something to life."},
    {"idiom": "自相矛盾", "pronunciation": "zì xiāng máo dùn", "translation": "Contradicting oneself with spear and shield",
     "explanation": "Being self-contradictory; inconsistent."},
    {"idiom": "拔苗助长", "pronunciation": "bá miáo zhù zhǎng", "translation": "Pulling sprouts to help them grow",
     "explanation": "Being counterproductively impatient; ruining something by excessive enthusiasm."},
    {"idiom": "叶公好龙", "pronunciation": "yè gōng hào lóng", "translation": "Lord Ye's love of dragons",
     "explanation": "Professing to like something while actually fearing it; hypocrisy."},
    {"idiom": "画饼充饥", "pronunciation": "huà bǐng chōng jī", "translation": "Drawing cakes to satisfy hunger",
     "explanation": "Seeking comfort in fantasy; daydreaming."},
    {"idiom": "滥竽充数", "pronunciation": "làn yú chōng shù", "translation": "Playing the yu to make up numbers",
     "explanation": "Filling a position without the necessary qualifications."},
    {"idiom": "囫囵吞枣", "pronunciation": "hú lún tūn zǎo", "translation": "Swallowing a date whole",
     "explanation": "Learning or doing something without understanding it properly."},
    {"idiom": "刻舟求剑", "pronunciation": "kè zhōu qiú jiàn", "translation": "Marking the boat to find a sword",
     "explanation": "Rigidly adhering to outdated methods; inflexibility."},
    {"idiom": "完璧归赵", "pronunciation": "wán bì guī zhào", "translation": "Returning the jade intact to Zhao",
     "explanation": "Returning something intact to its rightful owner."},
    {"idiom": "破釜沉舟", "pronunciation": "pò fǔ chén zhōu", "translation": "Breaking the pots and sinking the boats",
     "explanation": "Burning one's bridges; committing all one's resources to a course of action."},
    {"idiom": "背水一战", "pronunciation": "bèi shuǐ yī zhàn", "translation": "Fighting with one's back to the river",
     "explanation": "Making a final desperate effort; giving it your all."},
    {"idiom": "闻鸡起舞", "pronunciation": "wén jī qǐ wǔ", "translation": "Rising to dance upon hearing the rooster",
     "explanation": "Being diligent and seizing the moment; working hard from dawn."},
    {"idiom": "愚公移山", "pronunciation": "yú gōng yí shān", "translation": "The foolish old man who moved mountains",
     "explanation": "Perseverance in the face of hardship; determination conquers all."},
    {"idiom": "精卫填海", "pronunciation": "jīng wèi tián hǎi", "translation": "Jingwei trying to fill the sea",
     "explanation": "Carrying out an impossible task with unwavering determination."},
    {"idiom": "狡兔三窟", "pronunciation": "jiǎo tù sān kū", "translation": "A crafty rabbit has three burrows",
     "explanation": "Having multiple backup plans; being well-prepared."},
    {"idiom": "亡羊补牢", "pronunciation": "wáng yáng bǔ láo", "translation": "Mending the pen after losing the sheep",
     "explanation": "It's never too late to remedy a mistake."},
    {"idiom": "东施效颦", "pronunciation": "dōng shī xiào pín", "translation": "Dongshi imitating Xishi's frown",
     "explanation": "A clumsy imitation that misses the essence; poor imitation."},
    {"idiom": "买椟还珠", "pronunciation": "mǎi dú huán zhū", "translation": "Buying the case and returning the pearl",
     "explanation": "Focusing on the trivial while overlooking the essential."},
    {"idiom": "缘木求鱼", "pronunciation": "yuán mù qiú yú", "translation": "Climbing a tree to catch fish",
     "explanation": "Using a wrong method to pursue a goal; being impractical."},
    {"idiom": "班门弄斧", "pronunciation": "bān mén nòng fǔ", "translation": "Showing off one's axe before Lu Ban the master carpenter",
     "explanation": "Showing off before an expert; overestimating oneself."},
    {"idiom": "邯郸学步", "pronunciation": "hán dān xué bù", "translation": "Learning to walk in the style of Handan",
     "explanation": "Imitating others but losing one's own abilities in the process."},
    {"idiom": "管中窥豹", "pronunciation": "guǎn zhōng kuī bào", "translation": "Viewing a leopard through a tube",
     "explanation": "Seeing only a part and missing the whole; limited perspective."},
    {"idiom": "盲人摸象", "pronunciation": "máng rén mō xiàng", "translation": "Blind men touching an elephant",
     "explanation": "Understanding only one aspect of something while missing the bigger picture."},
    {"idiom": "鹬蚌相争", "pronunciation": "yù bàng xiāng zhēng", "translation": "The snipe and the clam grapple",
     "explanation": "A deadlock where both parties lose; mutual destruction."},
    {"idiom": "三人成虎", "pronunciation": "sān rén chéng hǔ", "translation": "Three men make a tiger",
     "explanation": "A rumor repeated often enough becomes accepted as truth."},
    {"idiom": "鱼目混珠", "pronunciation": "yú mù hùn zhū", "translation": "Passing off fish eyes as pearls",
     "explanation": "Passing off something fake as genuine; deception."},
    {"idiom": "南辕北辙", "pronunciation": "nán yuán běi zhé", "translation": "Heading south by driving the chariot north",
     "explanation": "Doing the opposite of what one intends; actions contradicting goals."},
    {"idiom": "反客为主", "pronunciation": "fǎn kè wéi zhǔ", "translation": "The guest becomes the host",
     "explanation": "The subsidiary becoming the dominant factor; reversal of roles."},
    {"idiom": "刮目相看", "pronunciation": "guā mù xiāng kàn", "translation": "Looking at someone with new eyes",
     "explanation": "Viewing someone with newfound respect; changing one's opinion."},
    {"idiom": "知己知彼", "pronunciation": "zhī jǐ zhī bǐ", "translation": "Know yourself, know your enemy",
     "explanation": "Understanding both sides of a situation leads to success."},
    {"idiom": "一石二鸟", "pronunciation": "yī shí èr niǎo", "translation": "One stone, two birds",
     "explanation": "Accomplishing two things with one effort; killing two birds with one stone."},
    {"idiom": "运筹帷幄", "pronunciation": "yùn chóu wéi wò", "translation": "Planning in the command tent",
     "explanation": "Making strategic decisions; careful planning."},
    {"idiom": "草木皆兵", "pronunciation": "cǎo mù jiē bīng", "translation": "Every grass and tree appears to be a soldier",
     "explanation": "Being extremely nervous or paranoid; seeing threats everywhere."},
    {"idiom": "望梅止渴", "pronunciation": "wàng méi zhǐ kě", "translation": "Quenching thirst by looking at plums",
     "explanation": "Trying to satisfy a desire through imagination alone; wishful thinking."},
    {"idiom": "守口如瓶", "pronunciation": "shǒu kǒu rú píng", "translation": "Keeping one's mouth shut like a bottle",
     "explanation": "Being tight-lipped; keeping secrets well."},
    {"idiom": "一叶障目", "pronunciation": "yī yè zhàng mù", "translation": "A leaf blocking the view",
     "explanation": "Being blinded by a minor detail; missing the bigger picture."},
    {"idiom": "高山流水", "pronunciation": "gāo shān liú shuǐ", "translation": "High mountains and flowing water",
     "explanation": "Beautiful music; close friendship with mutual appreciation."},
    {"idiom": "坐享其成", "pronunciation": "zuò xiǎng qí chéng", "translation": "Sitting and enjoying the fruits of others' labor",
     "explanation": "Reaping benefits without contributing effort; freeloading."},
    {"idiom": "临渊羡鱼", "pronunciation": "lín yuān xiàn yú", "translation": "Standing by a pond coveting fish",
     "explanation": "Desiring something but not taking action to obtain it."},
    {"idiom": "釜底抽薪", "pronunciation": "fǔ dǐ chōu xīn", "translation": "Removing firewood from under the cauldron",
     "explanation": "Tackling a problem at its root; addressing the fundamental cause."},
    {"idiom": "杀鸡儆猴", "pronunciation": "shā jī jǐng hóu", "translation": "Killing a chicken to scare the monkeys",
     "explanation": "Punishing one as a warning to others; making an example of someone."},
    {"idiom": "画地为牢", "pronunciation": "huà dì wéi láo", "translation": "Drawing a circle on the ground as a prison",
     "explanation": "Setting arbitrary limits for oneself; self-imposed restrictions."},
    {"idiom": "指鹿为马", "pronunciation": "zhǐ lù wéi mǎ", "translation": "Calling a deer a horse",
     "explanation": "Deliberately misrepresenting things; twisting facts."},
    {"idiom": "顺手牵羊", "pronunciation": "shùn shǒu qiān yáng", "translation": "Leading away a sheep in passing",
     "explanation": "Taking something opportunistically; stealing when the chance arises."},
    {"idiom": "风声鹤唳", "pronunciation": "fēng shēng hè lì", "translation": "The sound of wind and the cry of cranes",
     "explanation": "Being overly alarmed or jumpy; extreme nervousness."},
    {"idiom": "讳疾忌医", "pronunciation": "huì jí jì yī", "translation": "Concealing illness and avoiding doctors",
     "explanation": "Refusing to face or solve a problem; denial."},
    {"idiom": "度日如年", "pronunciation": "dù rì rú nián", "translation": "Each day feels like a year",
     "explanation": "Time passing extremely slowly; tedium."},
    {"idiom": "忍辱负重", "pronunciation": "rěn rǔ fù zhòng", "translation": "Bearing insults and shouldering burdens",
     "explanation": "Enduring humiliation to accomplish an important mission."},
    {"idiom": "兔死狐悲", "pronunciation": "tù sǐ hú bēi", "translation": "The fox mourns the death of the rabbit",
     "explanation": "Feeling sadness or sympathy due to shared circumstances or fate."},
    {"idiom": "鸡飞蛋打", "pronunciation": "jī fēi dàn dǎ", "translation": "The hen flies away and the eggs are broken",
     "explanation": "Complete failure; ending up with nothing."},
    {"idiom": "隔岸观火", "pronunciation": "gé àn guān huǒ", "translation": "Watching a fire from across the river",
     "explanation": "Observing others' misfortunes from a safe distance; detached observation."},
    {"idiom": "痛定思痛", "pronunciation": "tòng dìng sī tòng", "translation": "Reflecting on pain after the pain has subsided",
     "explanation": "Learning from past mistakes; reflection after suffering."},
    {"idiom": "枯木逢春", "pronunciation": "kū mù féng chūn", "translation": "Dead wood meeting spring",
     "explanation": "A revival of fortune; unexpected renewal."},
    {"idiom": "纸醉金迷", "pronunciation": "zhǐ zuì jīn mí", "translation": "Intoxicated by paper (money) and gold",
     "explanation": "A decadent, extravagant lifestyle; hedonistic pursuits."},
    {"idiom": "见微知著", "pronunciation": "jiàn wēi zhī zhù", "translation": "Seeing the small to know the great",
     "explanation": "Discerning the whole from a small part; noticing early warning signs."},
    {"idiom": "东山再起", "pronunciation": "dōng shān zài qǐ", "translation": "Rising again from the Eastern Mountain",
     "explanation": "Making a comeback after failure; career revival."},
    {"idiom": "不耻下问", "pronunciation": "bù chǐ xià wèn", "translation": "Not ashamed to ask inferiors",
     "explanation": "Willing to learn from anyone; no shame in asking questions."},
    {"idiom": "爱屋及乌", "pronunciation": "ài wū jí wū", "translation": "Loving the house and its crows",
     "explanation": "Extending love to a person's surroundings or associates; love by association."},
    {"idiom": "泰山鸿毛", "pronunciation": "tài shān hóng máo", "translation": "Mount Tai and a feather",
     "explanation": "Distinguishing between what is important and what is trivial."},
    {"idiom": "盛气凌人", "pronunciation": "shèng qì líng rén", "translation": "Overbearing attitude towards others",
     "explanation": "Being arrogant and domineering; treating others with contempt."},
    {"idiom": "望洋兴叹", "pronunciation": "wàng yáng xīng tàn", "translation": "Gazing at the sea and sighing",
     "explanation": "Feeling awe or helplessness when faced with something beyond one's capabilities."},
    {"idiom": "半途而废", "pronunciation": "bàn tú ér fèi", "translation": "Stopping halfway",
     "explanation": "Giving up before completion; leaving something unfinished."},
    {"idiom": "饮鸩止渴", "pronunciation": "yǐn zhèn zhǐ kě", "translation": "Drinking poison to quench thirst",
     "explanation": "Resorting to harmful methods for temporary relief; short-sighted solutions."},
    {"idiom": "强弩之末", "pronunciation": "qiáng nǔ zhī mò", "translation": "The last strength of a powerful crossbow",
     "explanation": "Diminishing power or momentum; the final stages of something once powerful."},
    {"idiom": "拍案惊奇", "pronunciation": "pāi àn jīng qí", "translation": "Slapping the table in amazement",
     "explanation": "Being greatly surprised or astonished; exclamation of wonder."},
    {"idiom": "杞人忧天", "pronunciation": "qǐ rén yōu tiān", "translation": "The man of Qi who feared the sky would fall",
     "explanation": "Needless anxiety; worrying about the impossible."},
    {"idiom": "梦寐以求", "pronunciation": "mèng mèi yǐ qiú", "translation": "Sought after in dreams",
     "explanation": "Something long desired or sought after; a cherished goal."},
    {"idiom": "抱薪救火", "pronunciation": "bào xīn jiù huǒ", "translation": "Carrying firewood to put out a fire",
     "explanation": "Making a situation worse by trying to help; counterproductive action."},
    {"idiom": "事半功倍", "pronunciation": "shì bàn gōng bèi", "translation": "Half the effort, double the result",
     "explanation": "Achieving greater results with less effort; efficiency."},
    {"idiom": "雪中送炭", "pronunciation": "xuě zhōng sòng tàn", "translation": "Sending charcoal in snowy weather",
     "explanation": "Providing timely assistance when it is most needed."},
    {"idiom": "落井下石", "pronunciation": "luò jǐng xià shí", "translation": "Throwing stones at someone who has fallen into a well",
     "explanation": "Attacking someone who is already in trouble; kicking someone when they're down."},
    {"idiom": "一丝不苟", "pronunciation": "yī sī bù gǒu", "translation": "Not neglecting a single thread",
     "explanation": "Being extremely careful and meticulous; paying attention to every detail."},
    {"idiom": "大器晚成", "pronunciation": "dà qì wǎn chéng", "translation": "Great talents mature late",
     "explanation": "Excellence takes time to develop; late bloomer."},
    {"idiom": "脚踏实地", "pronunciation": "jiǎo tà shí dì", "translation": "Feet firmly on the ground",
     "explanation": "Being practical and realistic; taking a down-to-earth approach."},
    {"idiom": "出类拔萃", "pronunciation": "chū lèi bá cuì", "translation": "Standing out from the crowd",
     "explanation": "Being outstanding or exceptional; excelling above others."},
    {"idiom": "集思广益", "pronunciation": "jí sī guǎng yì", "translation": "Gathering wisdom for the greater benefit",
     "explanation": "Pooling ideas for the common good; brainstorming."},
    {"idiom": "举一反三", "pronunciation": "jǔ yī fǎn sān", "translation": "Inferring three from one",
     "explanation": "Drawing inferences from limited information; learning by analogy."},
    {"idiom": "深思熟虑", "pronunciation": "shēn sī shú lǜ", "translation": "Deep thought and careful consideration",
     "explanation": "Thinking things through thoroughly; careful deliberation."},
    {"idiom": "言必有中", "pronunciation": "yán bì yǒu zhòng", "translation": "Words must hit the mark",
     "explanation": "Speaking accurately and to the point; being precise in one's statements."},
    {"idiom": "返璞归真", "pronunciation": "fǎn pú guī zhēn", "translation": "Return to nature",
     "explanation": "Returning to a simple, natural state; embracing simplicity."},
    {"idiom": "百尺竿头", "pronunciation": "bǎi chǐ gān tóu", "translation": "At the top of a hundred-foot pole",
     "explanation": "Achieving a high level of success but needing to continue advancing."},
]

# Clear existing data 
Idiom.objects.all().delete()

# Insert data into the database
for data in idioms_data:
    idiom = Idiom(
        idiom=data["idiom"],
        pronunciation=data["pronunciation"],
        translation=data["translation"],
        explanation=data["explanation"],
    )
    idiom.save()

print("Data inserted successfully!")